server:
  port: 80
  error:
    include-message: always
spring:
  application:
    name: civil-data
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    #url: jdbc:h2:mem:mydb
    url: jdbc:h2:file:./data/civil
    username: admin
    password: admin
    driverClassName: org.h2.Driver
    filters: stat
    maxActive: 50
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 50
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 30000
      maximum-pool-size: 50
      max-lifetime: 1800000
      minimum-idle: 10
      validation-timeout: 3000
      idle-timeout: 60000
      pool-name: CivilConnPool
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      connection:
        provider_class: "com.zaxxer.hikari.hibernate.HikariConnectionProvider"
      show-sql: false
  activemq:
    broker-url: vm://embedded?broker.persistent=false,useShutdownHook=false
    in-memory: true
    non-blocking-redelivery: true
    packages:
      trust-all: false
      trusted: com.memorynotfound
    pool:
      block-if-full: true
      block-if-full-timeout: -1
      enabled: false
      idle-timeout: 30000
      max-connections: 1
      time-between-expiration-check: -1
      use-anonymous-producers: true
  jms:
    listener:
      acknowledge-mode: auto
      auto-startup: true
      concurrency: 5
      max-concurrency: 10
    pub-sub-domain: false
    template:
      default-destination:
      delivery-mode: non_persistent
      priority: 100
      qos-enabled: true
      receive-timeout: 1000
      time-to-live: 36000
  profiles:
    active: dev
swagger:
  host: "localhost:80"
rest:
  client:
    sslbypass: true
    readTimeout: 20000
    maxConnectionTotal: 2000
    defaultMaxRoute: 2000
logging:
  level:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: error
